### PR TITLE
Created Installer

### PR DESCRIPTION
**Pull request by medmondson**
In response to #82 I've created an installer (.msi) which installs CShell along will all dependencies and a start menu item.

@lukebuehler I've tested this thoroughly although I'm not convinced the initial load of the workspaces is correct (along with the tutorial etc), therefore it would be worth you checking out if you're happy with this.  In addition feel free to modify the EULA as you're probably better placed to do that.

Any installer features or bugs I'd be more than happy to sort out - just let me know.

### CODE REVIEW

**Comment by lukebuehler** [comment]
This looks awesome, I'm really impressed!
I'm gonna merge this ASAP.

Two things that I've noticed:
1. Why did you add all the x86 and x64 targets? Is it possible to keep it simply a AnyCPU app?
2. The .cshell does not exist anymore. Is there a reason why you've added it back?

**Comment by medmondson** [comment]
Great, glad you're impressed.  To answer your questions:
1. Looks like VS auto added them although without loading it up I'm not sure why.  I'm happy we can remove them though leaving the file AnyCPU exclusive.
2. Is that Empty.cshell and Default.cshell?  I got those from the .zip download.  When I was putting the installer together I added the contents of this under the assumption they're all required.  If they're not that's fine - we can remove.

Happy to work on these if you don't fancy it?

**Update**
The Wix installers only run in x86 ([without a bit of extra work](http://stackoverflow.com/questions/18628790/build-wix-3-6-project-targeting-x64)) so that'll be the reason VS modified the .sln bitness flags.  I've removed the .cshell files.

**Comment by medmondson** [comment]
Thoughts on the current state of the PR?

**Comment by lukebuehler** [comment]
@medmondson sorry for the long delay, had a lot on my plate. 

It looks really great! Thank you.

In any case I just got around merging this, I made a few small changes, and I had this problem:
http://stackoverflow.com/questions/14879411/wix-ice-validation-errors

I have to investigate more, but when I launch the installed CShell project it crashes, we'll have to investigate. Could you take a look at this?

**Comment by medmondson** [comment]
No problem. If you assign the new issue to me I'll pick up ASAP.

**Pull request merged**
