### PR TITLE
Added tests for CShell ReplExecutor

### PR DESCRIPTION
**Pull request by marchuanv**
Added some NUnit tests for the ReplExecutor  execute scripts and commands.

### CODE REVIEW

**Comment by lukebuehler** [comment]
@marchuanv thanks, looks really great. Let me take a look ASAP, so I can plan the integration of the unit tests well.

**Comment by marchuanv** [comment]
Thanks I will continue adding some more NUnit tests once you've planned the integration.

**Comment by lukebuehler** [comment]
@marchuanv I know this has been a while! Merging now.

**Comment by lukebuehler** [comment]
@marchuanv, hmm your pull request is not available anymore ;-(

**Pull request merged**
